@jwt = token
@InventoryWarehouseAPI_HostAddress = http://localhost:5263

GET {{InventoryWarehouseAPI_HostAddress}}/weatherforecast/
Accept: application/json
Authorization: Bearer {{eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjAxOTc3ZjM2LTRhM2ItN2M2OS1hMjE1LTZlNDRlMzQ0ODdkMCIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6ImFkbWluQGV4YW1wbGUuY29tIiwiZXhwIjoxNzUwMjA0MDU4LCJpc3MiOiJJbnZlbnRvcnlXYXJlaG91c2VBUEkiLCJhdWQiOiJJbnZlbnRvcnlXYXJlaG91c2VBUEkifQ.SaJFbpELwwsDbqNIAmfHb75YodKR2ukU0cBdGskdlog}}

###
